#! /usr/bin/env python
# -*- coding: utf-8 -*-

from snakemake.utils import min_version
from os.path import splitext

min_version("6.4.1")

configfile: "config/config.yaml"

wildcard_constraints:
    fasta_base = '[\w\-. ]+\.(fasta|fa|fna)$'

include: "rules/remote.smk"
include: "rules/extract.smk"
include: "rules/star_index.smk"
include: "rules/repeat_annotation.smk"

rule all:
    input:
        rules.star_index_gdc38_gencode38.output,
        rules.star_index_ncbi38_gencode38.output

       
